# prometheus-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: telemetry
  labels:
    app: prometheus
    component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # Dostosuj rozmiar
  # storageClassName: "your-storage-class" # Opcjonalnie
