AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create an Amazon EKS Cluster (using existing IAM role) and a Managed Node Group.

Parameters:
  # CLUSTER CONFIG START
  ClusterName:
    Type: String
    Default: suu-vitess-cluster
    Description: The name for the EKS cluster.

  ClusterVersion:
    Type: String
    Default: "1.32"
    Description: The Kubernetes version for the EKS cluster.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the EKS cluster will be created.
  # CLUSTER CONFIG END
  # NODE GROUP CONFIG START
  NodeGroupName:
    Type: String
    Default: suu-vitess-nodes
    Description: The name for the EKS node group.

  NodeInstanceType:
    Type: String
    Default: t3.medium
    Description: The EC2 instance type for the worker nodes.

  NodeGroupDesiredSize:
    Type: Number
    Default: 2
    Description: The desired number of worker nodes in the node group.

  NodeGroupMinSize:
    Type: Number
    Default: 2
    Description: The minimum number of worker nodes in the node group.

  NodeGroupMaxSize:
    Type: Number
    Default: 2
    Description: The maximum number of worker nodes in the node group.
  # NODE GROUP CONFIG END
  # COMMON CONFIG START
  EksRoleArn:
    Type: String
    Description: The ARN of the existing IAM role for the EKS cluster (e.g., arn:aws:iam::123456789012:role/LabRole). This role must have the necessary EKS policies attached.

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of subnet IDs for the EKS cluster and worker nodes.
  # COMMON CONFIG END
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref ClusterVersion
      RoleArn: !Ref EksRoleArn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds

  CoreDnsAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: coredns

  NodeMonitoringAgentAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: eks-node-monitoring-agent

  VPCCNIAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: vpc-cni

  KubeProxyAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: kube-proxy

  EKSPodIdentityAgentAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: eks-pod-identity-agent

  ExternalDNSAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: external-dns

  MetricsServerAddon:
    Type: AWS::EKS::Addon
    Properties:
      ClusterName: !Ref EKSCluster
      AddonName: metrics-server

  EKSNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      AmiType: AL2023_x86_64_STANDARD
      CapacityType: ON_DEMAND
      ClusterName: !Ref EKSCluster
      DiskSize: 20
      InstanceTypes:
        - !Ref NodeInstanceType
      NodegroupName: !Ref NodeGroupName
      NodeRole: !Ref EksRoleArn
      ScalingConfig:
        DesiredSize: !Ref NodeGroupDesiredSize
        MinSize: !Ref NodeGroupMinSize
        MaxSize: !Ref NodeGroupMaxSize
      Subnets: !Ref SubnetIds
