insert into pokemon (name, type, level) values
('Pikachu', 'Electric', 15),
('Charmander', 'Fire', 12),
('Bulbasaur', 'Grass/Poison', 10),
('Squirtle', 'Water', 11),
('Dracoflame', 'Dragon/Fire', 20),         
('Aquarock', 'Water/Rock', 18),           
('Leafawn', 'Grass/Fairy', 14),           
('Zaptiger', 'Electric/Dark', 22),        
('Glacierine', 'Ice/Ghost', 25),          
('Infernox', 'Fire/Steel', 28),           
('Jolteon', 'Electric', 17),
('Gengar', 'Ghost/Poison', 26),
('Lucario', 'Fighting/Steel', 30),
('Blazehawk', 'Fire/Flying', 21),          
('Toxifang', 'Poison/Dark', 19),           
('Cryowl', 'Ice/Flying', 16),              
('Stonox', 'Rock/Steel', 24),              
('Glimmora', 'Fairy/Psychic', 27),         
('Venustoise', 'Grass/Water', 30),
('Electhorn', 'Electric/Steel', 32),       
('Shadowleon', 'Ghost/Fighting', 29),      
('Sylveon', 'Fairy', 20),
('Metagross', 'Steel/Psychic', 35),
('Tyranitar', 'Rock/Dark', 36),
('Garchomp', 'Dragon/Ground', 37),
('Lunara', 'Psychic/Dark', 40);

insert into trainer (name, region) values
('Erika', 'Kanto'),
('Lance', 'Johto'),
('Flint', 'Sinnoh'),
('Iris', 'Unova'),
('Talon', 'Volaria'),       
('Nova', 'Solara'),         
('Kai', 'Maris'),           
('Skye', 'Altara');         

