# grafana-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: telemetry # Możesz zmienić na swoją przestrzeń nazw
  labels:
    app: grafana
spec:
  selector:
    app: grafana # Musi pasować do etykiet podów Deploymentu
  ports:
    - name: http
      protocol: TCP
      port: 80 # Port, na którym serwis będzie dostępny
      targetPort: 3000 # Port kontenera Grafany
  type: ClusterIP # Dostępny tylko wewnątrz klastra
