# loki-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: telemetry
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001 # Loki domyślnie używa non-root użytkownika
        runAsUser: 10001
        runAsNonRoot: true
      containers:
      - name: loki
        image: grafana/loki:2.9.8 # Użyj stabilnej, konkretnej wersji
        args:
          - "-config.file=/etc/loki/loki-local-config.yaml"
        ports:
        - name: http-metrics
          containerPort: 3100
        - name: grpc
          containerPort: 9096
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: http-metrics
        #   initialDelaySeconds: 45
        # livenessProbe:
        #   httpGet:
        #     path: /ready
        #     port: http-metrics
        #   initialDelaySeconds: 45
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: storage
          mountPath: /loki # Musi pasować do common.path_prefix w konfiguracji Loki
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 1Gi
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: storage
        persistentVolumeClaim:
          claimName: loki-pvc
