# loki-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: telemetry
  labels:
    app: loki
data:
  loki-local-config.yaml: |
    auth_enabled: false # W prostym setupie wyłączamy autoryzację

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /loki # Ścieżka w PVC, gdzie Loki będzie przechowywał dane
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1 # Dla pojedynczej instancji
      ring:
        instance_addr: 127.0.0.1 # Dla pojedynczej instancji
        kvstore:
          store: inmemory # Używa pamięci dla ringa (niezalecane dla produkcji, ale proste)

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper # Używa BoltDB Shipper, zalecane dla pojedynczych instancji i skalowalności
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    ruler: # Włączamy ruler, jeśli chcemy używać alertów z logów
      alertmanager_url: http://localhost:9093 # Jeśli masz Alertmanager, podaj jego URL

    # Jeśli nie używasz BoltDB Shipper i chcesz prostszy BoltDB (mniej zalecane)
    # index_cache:
    #   boltdb:
    #     directory: /loki/index_cache

    # storage_config:
    #   boltdb:
    #     directory: /loki/index

    # chunk_store_config:
    #   max_look_back_period: 0s

    # table_manager:
    #   retention_deletes_enabled: true
    #   retention_period: 336h # 2 tygodnie retencji
